from __future__ import annotations
from pathlib import Path
from jinja2 import Template

TPL = r'''
<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ title }}</title>
<style>
:root{--bg:#f3f4f6;--card:#fff;--text:#111827;--muted:#6b7280;--line:#e5e7eb;--up:#d62828;--down:#14804a;--accent:#f4b400;--warn:#b45309}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,"Microsoft JhengHei",sans-serif}.wrap{max-width:1220px;margin:20px auto;padding:0 14px}
.card{background:var(--card);border-radius:16px;padding:18px;margin-bottom:14px;box-shadow:0 5px 20px rgba(0,0,0,.06)}h1{margin:0;font-size:28px}.lead{font-size:20px;font-weight:800;margin-top:10px;line-height:1.5}.muted{font-size:12px;color:var(--muted)}h2{font-size:18px;margin:0 0 10px}h3{margin:8px 0;font-size:15px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px}.pick,.mini{border:1px solid var(--line);border-radius:12px;padding:13px}.up{color:var(--up)}.down{color:var(--down)}
table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:8px;border-bottom:1px solid var(--line);text-align:right;vertical-align:top}th:first-child,td:first-child{text-align:left}.small{font-size:12px;line-height:1.7}.tag{display:inline-block;padding:3px 9px;border-radius:999px;background:#fff4cc;margin:3px 5px 3px 0}.scroll{overflow-x:auto}.empty{color:var(--muted);padding:6px 0}.stars{font-size:19px;color:#e6a700;letter-spacing:1px}.risk-low{color:#15803d}.risk-mid{color:#b45309}.risk-high{color:#b91c1c}.status{font-weight:800}.status-normal{color:#15803d}.status-attn{color:#b45309}.status-punish{color:#b91c1c}.reason-list{margin:7px 0;padding-left:18px}.reason-list li{margin:3px 0}.kchart{width:100%;height:auto;display:block;background:#fff;border:1px solid var(--line);border-radius:12px}.chart-wrap{margin-top:10px}.pick-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.pick-title{font-weight:800}.badge{display:inline-block;border-radius:999px;padding:3px 8px;background:#f3f4f6;font-size:12px;margin:2px}.notice-box{background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:9px;margin-top:8px}.punish-box{background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:9px;margin-top:8px}.brief{border-left:5px solid var(--accent)}.brief-text{font-size:16px;line-height:1.8;font-weight:650}.impact-list{margin:6px 0 0;padding-left:18px}.status-detail{margin-top:8px;line-height:1.65}.chart-legend{font-size:11px;color:var(--muted)}
@media(max-width:720px){table{font-size:11px;min-width:1120px}.lead{font-size:17px}.card{padding:12px}.pick-top{display:block}.stars{margin-top:5px}}
</style></head><body><div class="wrap">
<div class="card"><div class="muted">{{ version }}｜報告交易日 {{ trade_date }}｜產生時間 {{ generated }}</div><h1>台股前一交易日晨報</h1><div class="lead">{{ one_liner }}</div></div>
<div class="card brief"><h2>市場摘要</h2><div class="brief-text">{{ market_brief }}</div><h3>今日觀察</h3><ul class="reason-list">{% for x in market_watch %}<li>{{ x }}</li>{% endfor %}</ul></div>
<div class="grid"><div class="card"><h2>國際盤</h2>{% for x in global_lines %}<div>• {{ x }}</div>{% endfor %}</div><div class="card"><h2>三大法人</h2>{% for x in institution_summary %}<div>• {{ x }}</div>{% endfor %}<div class="muted">由個股法人資料彙總，單位為新台幣億元。</div></div></div>
<div class="card"><h2>加權指數 K 線</h2><div class="chart-wrap">{{ market_chart_svg }}</div><div>{{ market_summary }}</div><div><span class="tag">支撐 {{ market_support }}</span><span class="tag">壓力 {{ market_resistance }}</span><span class="tag">趨勢 {{ market_trend }}</span></div><div class="muted">資料源：{{ market_source }}</div></div>
<div class="card"><h2>利多／利空</h2><div class="grid"><div class="mini"><b class="up">利多</b>{% for n in bull %}<div>• {% if n.link %}<a href="{{ n.link }}" target="_blank" rel="noopener">{{ n.title }}</a>{% else %}{{ n.title }}{% endif %}</div>{% endfor %}</div><div class="mini"><b class="down">利空</b>{% for n in bear %}<div>• {% if n.link %}<a href="{{ n.link }}" target="_blank" rel="noopener">{{ n.title }}</a>{% else %}{{ n.title }}{% endif %}</div>{% endfor %}</div></div></div>
<div class="card"><h2>當沖觀察</h2><div class="muted">星級代表條件完整度，不代表保證獲利。進場區間是觀察區，開盤仍須確認量價與大盤方向。</div><div class="grid">{% for p in picks %}<div class="pick"><div class="pick-top"><div><div class="pick-title {{ 'up' if p.side=='多' else 'down' }}">{{ p.code }} {{ p.name }}｜{{ p.side }}</div><div class="stars">{{ p.stars_text }}</div></div><div><span class="badge {{ 'risk-low' if p.risk=='低' else 'risk-mid' if p.risk=='中' else 'risk-high' }}">風險 {{ p.risk }}</span><span class="badge {{ 'status-normal' if p.status=='正常' else 'status-attn' if p.status=='注意' else 'status-punish' }}">{{ p.status }}股</span></div></div><div>{{ p.reason }}</div><h3>推薦依據</h3><ul class="reason-list">{% for x in p.recommend_reasons %}<li>✓ {{ x }}</li>{% else %}<li>目前沒有明顯加分條件</li>{% endfor %}</ul>{% if p.risk_reasons %}<h3>風險因素</h3><ul class="reason-list">{% for x in p.risk_reasons %}<li>⚠ {{ x }}</li>{% endfor %}</ul>{% endif %}{% if p.status!='正常' %}<div class="{{ 'notice-box' if p.status=='注意' else 'punish-box' }}"><b>{{ '⚠ 注意股' if p.status=='注意' else '🚨 處置股' }}</b><div class="status-detail"><b>列入原因：</b>{{ p.status_reason }}</div>{% if p.status_start or p.status_end %}<div><b>期間：</b>{{ p.status_start or '未解析' }} ～ {{ p.status_end or '未解析' }}</div>{% elif p.status_period %}<div><b>公告期間：</b>{{ p.status_period }}</div>{% endif %}{% if p.status_measure %}<div><b>交易措施：</b>{{ p.status_measure }}</div>{% endif %}{% if p.status_impact %}<div><b>對交易的影響：</b><ul class="impact-list">{% for x in p.status_impact %}<li>{{ x }}</li>{% endfor %}</ul></div>{% endif %}</div>{% endif %}<div class="small">觀察區 {{ p.entry }}｜防守 {{ p.stop }}｜目標 {{ p.target }}</div><details><summary>查看 K 線</summary><div class="chart-wrap">{{ p.chart_svg }}</div></details></div>{% else %}<div class="empty">目前沒有符合條件的標的，今天讓手指喝杯茶。</div>{% endfor %}</div></div>
<div class="card"><h2>成交值前 20 檔</h2><div class="scroll"><table><thead><tr><th>代號名稱</th><th>星級</th><th>風險</th><th>交易狀態</th><th>狀態原因</th><th>收盤</th><th>漲跌%</th><th>量比</th><th>法人淨額</th><th>趨勢</th><th>當沖傾向</th><th>防守價</th></tr></thead><tbody>{% for r in rows %}<tr><td>{{ r.code }} {{ r.name }}</td><td class="stars">{{ r.stars_text }}</td><td class="{{ 'risk-low' if r.risk=='低' else 'risk-mid' if r.risk=='中' else 'risk-high' }}">{{ r.risk }}</td><td class="{{ 'status-normal' if r.status=='正常' else 'status-attn' if r.status=='注意' else 'status-punish' }}">{{ r.status }}</td><td class="small" style="text-align:left;max-width:280px">{{ r.status_reason or '無' }}</td><td>{{ r.close }}</td><td class="{{ 'up' if r.pct>0 else 'down' if r.pct<0 else '' }}">{{ "%+.2f"|format(r.pct) }}</td><td>{{ "%.2f"|format(r.vol_ratio) }}</td><td>{{ r.inst_net }}</td><td>{{ r.trend }}</td><td>{{ r.bias }}</td><td>{{ r.stop }}</td></tr>{% endfor %}</tbody></table></div></div>
<div class="card"><details><summary><b>個股星級理由與 K 線</b></summary><div class="grid">{% for r in rows %}<div class="mini"><b>{{ r.code }} {{ r.name }}</b><div class="stars">{{ r.stars_text }}</div><div>風險：{{ r.risk }}｜狀態：{{ r.status }}</div><ul class="reason-list">{% for x in r.recommend_reasons %}<li>✓ {{ x }}</li>{% endfor %}{% for x in r.risk_reasons %}<li>⚠ {{ x }}</li>{% endfor %}</ul>{% if r.status!='正常' %}<div class="{{ 'notice-box' if r.status=='注意' else 'punish-box' }}"><b>{{ r.status }}原因：</b>{{ r.status_reason }}{% if r.status_start or r.status_end %}<br><b>期間：</b>{{ r.status_start or '未解析' }} ～ {{ r.status_end or '未解析' }}{% elif r.status_period %}<br><b>期間：</b>{{ r.status_period }}{% endif %}{% if r.status_measure %}<br><b>措施：</b>{{ r.status_measure }}{% endif %}{% if r.status_impact %}<ul class="impact-list">{% for x in r.status_impact %}<li>{{ x }}</li>{% endfor %}</ul>{% endif %}</div>{% endif %}{% if r.data_note %}<div class="notice-box">{{ r.data_note }}</div>{% endif %}<div class="chart-wrap">{{ r.chart_svg }}</div></div>{% endfor %}</div></details></div>
<div class="card"><details><summary><b>附錄與完整技術指標</b></summary><div class="small"><h3>訊號勝率</h3>{% for b in backtests %}<div>{{ b.signal }}：樣本 {{ b.samples }} 次，{{ b.label }} {{ b.wins }} 次（{{ b.rate }}%）{% if b.small %}，樣本過小僅供參考{% endif %}</div>{% endfor %}<h3>完整指標</h3>{% for r in rows %}<div>{{ r.code }} {{ r.name }}｜MA5 {{ r.ma5 }}｜MA20 {{ r.ma20 }}｜MA60 {{ r.ma60 }}｜EMA12 {{ r.ema12 }}｜EMA26 {{ r.ema26 }}｜K {{ r.k }}｜D {{ r.d }}｜MACD {{ r.macd }}｜RSI {{ r.rsi }}｜ATR {{ r.atr }}｜布林上 {{ r.bb_upper }}｜布林下 {{ r.bb_lower }}｜支撐 {{ r.support }}｜壓力 {{ r.resistance }}</div>{% endfor %}<h3>資料缺漏</h3>{% for n in notes %}<div>• {{ n }}</div>{% endfor %}</div></details></div>
<div class="card small">注意股是風險提示，不等於停止交易；處置措施與期間以證交所最新公告為準。免責聲明：本報告僅為公開資料與技術條件整理，不構成任何投資建議。當沖風險極高，交易人應自行判斷並承擔損益。<br>資料來源：臺灣證券交易所、Yahoo Finance、Google News RSS。</div>
</div></body></html>
'''

def write(path: Path, ctx: dict):
    path.write_text(Template(TPL).render(**ctx), encoding="utf-8")
